/* Hotel Reservation System schema */

DROP TABLE ROOM_ALLOCATIONS IF EXISTS;
DROP TABLE RESERVATIONS IF EXISTS;
DROP TABLE USERS IF EXISTS;
DROP TABLE ROOMS IF EXISTS;

CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(30) NOT NULL
);

CREATE TABLE ROOMS (
    ROOM_NUMBER VARCHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE RESERVATIONS (
    RESERVATION_NUMBER VARCHAR(50) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(50) NOT NULL,
    ROOM_NUMBER VARCHAR(20) NOT NULL,
    RESERVED_AT TIMESTAMP NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CONSTRAINT FK_RESERVATION_USER
        FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
    CONSTRAINT FK_RESERVATION_ROOM
        FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOMS (ROOM_NUMBER),
    CONSTRAINT CK_RESERVATION_STATUS
        CHECK (STATUS IN ('RESERVED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELED'))
);

CREATE TABLE ROOM_ALLOCATIONS (
    ROOM_NUMBER VARCHAR(20) NOT NULL,
    CHECK_IN_DATE DATE NOT NULL,
    RESERVATION_NUMBER VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ROOM_ALLOCATION PRIMARY KEY (ROOM_NUMBER, CHECK_IN_DATE),
    CONSTRAINT UQ_ALLOCATION_RESERVATION UNIQUE (RESERVATION_NUMBER),
    CONSTRAINT FK_ALLOCATION_ROOM
        FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOMS (ROOM_NUMBER),
    CONSTRAINT FK_ALLOCATION_RESERVATION
        FOREIGN KEY (RESERVATION_NUMBER) REFERENCES RESERVATIONS (RESERVATION_NUMBER)
);

INSERT INTO ROOMS VALUES ('1001');
INSERT INTO ROOMS VALUES ('1002');
INSERT INTO ROOMS VALUES ('1003');
INSERT INTO ROOMS VALUES ('1004');
INSERT INTO ROOMS VALUES ('1005');
